# Generated by Django 2.0.5 on 2018-07-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('imdb_link', models.CharField(max_length=1000)),
                ('year', models.CharField(max_length=4)),
                ('certificate', models.CharField(default=None, max_length=20)),
                ('runtime', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=100)),
                ('imdb_rating', models.CharField(max_length=3)),
                ('metascore', models.CharField(max_length=2)),
                ('director', models.CharField(max_length=100)),
                ('director_link', models.CharField(max_length=1000)),
                ('cast', models.CharField(max_length=1000)),
                ('cast_link', models.CharField(max_length=2000)),
                ('gross', models.CharField(max_length=20)),
            ],
        ),
    ]
