# Generated by Django 2.0.5 on 2018-07-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast_link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_link',
        ),
    ]
