# Generated by Django 2.0.5 on 2018-07-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180703_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('imdb_link', models.CharField(max_length=1000)),
                ('date_of_birh', models.CharField(max_length=100)),
                ('movies', models.CharField(max_length=2000)),
                ('profession', models.CharField(max_length=200)),
                ('birth_place', models.CharField(max_length=100)),
            ],
        ),
    ]
