# Generated by Django 2.0.5 on 2018-07-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='date_of_birh',
        ),
        migrations.RemoveField(
            model_name='director',
            name='id',
        ),
        migrations.AddField(
            model_name='director',
            name='date_of_birth',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='movie_links',
            field=models.CharField(default='None', max_length=4000),
        ),
        migrations.AlterField(
            model_name='director',
            name='imdb_link',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
