# Generated by Django 2.0.5 on 2018-07-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180706_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('logo', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('imdb_link', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('date_of_birth', models.CharField(default='None', max_length=100)),
                ('movies', models.CharField(max_length=2000)),
                ('movie_links', models.CharField(default='None', max_length=4000)),
                ('profession', models.CharField(max_length=200)),
                ('birth_place', models.CharField(max_length=100)),
            ],
        ),
    ]
