# Generated by Django 2.0.5 on 2018-07-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_link',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
